In [1]:
import sys
from collections import defaultdict
import math
import random
import os
import os.path
"""
COMS W4705 - Natural Language Processing
Homework 1 - Programming Component: Trigram Language Models
Yassine Benajiba
"""

def corpus_reader(corpusfile, lexicon=None): 
    with open(corpusfile,'r') as corpus: 
        for line in corpus: 
            if line.strip():
                sequence = line.lower().strip().split()
                if lexicon: 
                    yield [word if word in lexicon else "UNK" for word in sequence]
                else: 
                    yield sequence

def get_lexicon(corpus):
    word_counts = defaultdict(int)
    for sentence in corpus:
        for word in sentence: 
            word_counts[word] += 1
    return set(word for word in word_counts if word_counts[word] > 1)  



def get_ngrams(sequence, n):
    """
    COMPLETE THIS FUNCTION (PART 1)
    Given a sequence, this function should return a list of n-grams, where each n-gram is a Python tuple.
    This should work for arbitrary values of 1 <= n < len(sequence).
    """

    return []


class TrigramModel(object):
    
    def __init__(self, corpusfile):
    
        # Iterate through the corpus once to build a lexicon 
        generator = corpus_reader(corpusfile)
        self.lexicon = get_lexicon(generator)
        self.lexicon.add("UNK")
        self.lexicon.add("START")
        self.lexicon.add("STOP")
    
        # Now iterate through the corpus again and count ngrams
        generator = corpus_reader(corpusfile, self.lexicon)
        self.count_ngrams(generator)


    def count_ngrams(self, corpus):
        """
        COMPLETE THIS METHOD (PART 2)
        Given a corpus iterator, populate dictionaries of unigram, bigram,
        and trigram counts. 
        """
   
        self.unigramcounts = {} # might want to use defaultdict or Counter instead
        self.bigramcounts = {} 
        self.trigramcounts = {} 

        ##Your code here

        return

    def raw_trigram_probability(self,trigram):
        """
        COMPLETE THIS METHOD (PART 3)
        Returns the raw (unsmoothed) trigram probability
        """
        return 0.0

    def raw_bigram_probability(self, bigram):
        """
        COMPLETE THIS METHOD (PART 3)
        Returns the raw (unsmoothed) bigram probability
        """
        return 0.0
    
    def raw_unigram_probability(self, unigram):
        """
        COMPLETE THIS METHOD (PART 3)
        Returns the raw (unsmoothed) unigram probability.
        """

        #hint: recomputing the denominator every time the method is called
        # can be slow! You might want to compute the total number of words once, 
        # store in the TrigramModel instance, and then re-use it.  
        return 0.0

    def generate_sentence(self,t=20): 
        """
        COMPLETE THIS METHOD (OPTIONAL)
        Generate a random sentence from the trigram model. t specifies the
        max length, but the sentence may be shorter if STOP is reached.
        """
        return result            

    def smoothed_trigram_probability(self, trigram):
        """
        COMPLETE THIS METHOD (PART 4)
        Returns the smoothed trigram probability (using linear interpolation). 
        """
        lambda1 = 1/3.0
        lambda2 = 1/3.0
        lambda3 = 1/3.0
        return 0.0
        
    def sentence_logprob(self, sentence):
        """
        COMPLETE THIS METHOD (PART 5)
        Returns the log probability of an entire sequence.
        """
        return float("-inf")

    def perplexity(self, corpus):
        """
        COMPLETE THIS METHOD (PART 6) 
        Returns the log probability of an entire sequence.
        """
        return float("inf") 


def essay_scoring_experiment(training_file1, training_file2, testdir1, testdir2):

        model1 = TrigramModel(training_file1)
        model2 = TrigramModel(training_file2)

        total = 0
        correct = 0       
 
        for f in os.listdir(testdir1):
            pp = model1.perplexity(corpus_reader(os.path.join(testdir1, f), model1.lexicon))
            # .. 
    
        for f in os.listdir(testdir2):
            pp = model2.perplexity(corpus_reader(os.path.join(testdir2, f), model2.lexicon))
            # .. 
        
        return 0.0

if __name__ == "__main__":

    model = TrigramModel(sys.argv[1]) 

    # put test code here...
    # or run the script from the command line with 
    # $ python -i trigram_model.py [corpus_file]
    # >>> 
    #
    # you can then call methods on the model instance in the interactive 
    # Python prompt. 

    
    # Testing perplexity: 
    # dev_corpus = corpus_reader(sys.argv[2], model.lexicon)
    # pp = model.perplexity(dev_corpus)
    # print(pp)


    # Essay scoring experiment: 
    # acc = essay_scoring_experiment('train_high.txt', 'train_low.txt", "test_high", "test_low")
    # print(acc)



FileNotFoundError: [Errno 2] No such file or directory: '-f'

In [2]:
def count_ngrams(self, corpus):
    """
    COMPLETE THIS METHOD (PART 2)
    Given a corpus iterator, populate dictionaries of unigram, bigram,
    and trigram counts. 
    """

    self.unigramcounts = {} # might want to use defaultdict or Counter instead
    self.bigramcounts = {} 
    self.trigramcounts = {} 

    ##Your code here
    unigramcounts[0] = ("START",)
    while(corpus != null):
        
        
        # corpus = next(corpus)
    

    return

## Part 1

In [73]:
def get_ngrams(sequence, n):
    """
    COMPLETE THIS FUNCTION (PART 1)
    Given a sequence, this function should return a list of n-grams, where each n-gram is a Python tuple.
    This should work for arbitrary values of 1 <= n < len(sequence).
    """
    
    result = []
    
    # sequence.insert(0, "START")
    
    if (n == 1):
        sequence.insert(0, "START")
    else:
        for i in range(n-1):
            sequence.insert(i, "START")
    

    
    sequence.append("END")
    print(len(sequence))
    
    for i in range(len(sequence) - n+1): # should > len(seq)   # range 留头去尾 
        # print(i, i+n,sequence[i:i+n], tuple(sequence[i:i+n]))
        # result[i] = tuple(sequence[i:i+n])  # not a dict
        result.append(tuple(sequence[i:i+n]))

    return result

list1 = [1,2,3,4]

print(get_ngrams(list1, 3))



7
[('START', 'START', 1), ('START', 1, 2), (1, 2, 3), (2, 3, 4), (3, 4, 'END')]


list 切片

生成 tuple

修改一个值

append 函数 在结尾插入  O(1)

insert 函数 用于在中间插入 位置 值  O（1）

In [66]:
list1 = [1,2,3,4]
print(list1[1:3])

print(tuple(list1[0:0+2]))

list1[0] = 0
print(list1)

list1.append(5)
print(list1)

list1.insert(0,-1)
print(list1)

list1.insert(1,100)
print(list1)

for i in range(1):
    print("i",i)

[2, 3]
(1, 2)
[0, 2, 3, 4]
[0, 2, 3, 4, 5]
[-1, 0, 2, 3, 4, 5]
[-1, 100, 0, 2, 3, 4, 5]
i 0


In [63]:
print(tuple(list1[0:1]))

(-1,)


## Part2


In [56]:
sys.argv[1]

'-f'

In [57]:
len(sys.argv)

3

In [58]:
print(sys.argv)

['C:\\Users\\31557\\anaconda3\\lib\\site-packages\\ipykernel_launcher.py', '-f', 'C:\\Users\\31557\\AppData\\Roaming\\jupyter\\runtime\\kernel-211ee563-d77a-460a-8330-a2772ffbe420.json']


dict 不会自动初始化，第一次初始化 key 需要赋值。而 default dict 可以自动识别，没有的就初始化为0。在统计 ngram 时自增 可以保持操作的一致性，代码简洁。

如果只能用 dict 完成第一次初始化，可以用 try catch 第一次捕捉没有 key 的error 然后初始化为 1， 后续再 += 1

In [78]:
dict1 = {}
dict1["w1"] = 1

print(dict1)

{'w1': 1}


In [79]:
dict1["w1"] += 1
print(dict1)

dict1["w2"] += 1
print(dict1)

{'w1': 2}


KeyError: 'w2'

In [80]:
from collections import defaultdict

dict2 = defaultdict(int)

dict2["w1"] += 1

print(dict2)

defaultdict(<class 'int'>, {'w1': 1})


In [88]:
tuple1 = (1,2,3)
tuple1[0:2]
# tuple indices must be integers or slices,

(1, 2)

In [3]:
list2 = [('1',1), ('2',2) ]
print(list2)
list2[:,1]

[('1', 1), ('2', 2)]


In [9]:
list2 = [['1',1], ['2',2] ]
list2[:,1]

TypeError: list indices must be integers or slices, not tuple

In [13]:
import numpy as np
list2 = np.array([['1',1], ['2',2] ])
# list2[:,0]
print(list2)

[['1' '1']
 ['2' '2']]


In [25]:
dict2 = {'1':0.1, "2":0.7, "3":0.2}
print(dict2)

dict2.values(), list(dict2.values())

{'1': 0.1, '2': 0.7, '3': 0.2}


(dict_values([0.1, 0.7, 0.2]), [0.1, 0.7, 0.2])

In [60]:
draw = np.random.multinomial(1, list(dict2.values()), 1).flatten()
draw

array([0, 1, 0])

In [57]:
dict2[draw]

TypeError: unhashable type: 'numpy.ndarray'

In [45]:
dict2.keys()

TypeError: 'dict_keys' object is not subscriptable

In [61]:
for x, y in enumerate(dict2.values()):
    print(x,y)
    
    
# list3 = [ [x,y] for x, y in enumerate(dict2.values()) if y>=0.2  ]
list3 = [ [x,y] for x, y in enumerate(dict2.values()) ]
print(list3)

0 0.1
1 0.7
2 0.2
[[0, 0.1], [1, 0.7], [2, 0.2]]


In [62]:
np.array(list3)[:,1]

array([0.1, 0.7, 0.2])

In [64]:
draw = np.random.multinomial(1, np.array(list3)[:,1], 1).flatten()
draw

array([0, 1, 0])

In [86]:
print(np.where(draw == 0)[0])
print(np.where(draw == 1)[0][0])

[0 2]
1


In [87]:
list(dict2.keys())[np.where(draw == 1)[0][0]]

'2'

In [88]:
for i, j in enumerate(dict2):
    print(i,j)

0 1
1 2
2 3
